kind: pipeline
type: docker
name: default

# workspace:
#   path: /drone/src/kafka-autoconnector
   
steps:
- name: build
  pull: always
  image: golang:alpine
  commands:
  - echo "hello"

- name: publish-backend-image
  pull: always
  image: plugins/docker
  settings:
    dockerfile: backend/Dockerfile
    repo: ratsimat/task-app-fullstack
    tags:
      - latest
      # - ${DRONE_TAG}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    trigger:
      branch:
      - master
      event:
      - push
      # - tag
